### PR TITLE
Added support to match team names with crests used in /r/gunners subreddit

### PR DESCRIPTION
**Pull request by AndyReifman**

### CODE REVIEW

**Comment by vcanales** [comment]
Merged! Are you already using the bot, or still testing?

**Comment by AndyReifman** [comment]
Still working on testing. The big thing right now is that it wipes the entire sidebar on update, which is problematic as there are things other than the table there.

**Comment by vcanales** [comment]
Are you open to sending me an entire sidebar's markdown? I can probably make it so the bot grabs the sidebar content and replaces only the table.

**Comment by AndyReifman** [comment]
http://pastebin.com/0YEWAu5E Here's the general make-up of it. My thought would be read it all in and search for the key of "Premier League" Then just replace only that table.

**Comment by vcanales** [comment]
Great! I'll look into it tonight.

**Comment by vcanales** [comment]
Hey. It's been a while, but If we use comments to mark the different dynamic sections, we can make this pretty easy.

See: 

```
[//]: # (This may be the most platform independent comment)
```

So we could do: 

```
[//]: # ([SIDEBAR_SECTION:start:premier_league])
[//]: # ([SIDEBAR_SECTION:end:premier_league])
```

**Pull request merged**
